# Generated by Django 4.1.5 on 2023-02-18 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ваканции')),
                ('description', models.TextField(verbose_name='Описание ваканции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ваканция от пользователя',
                'verbose_name_plural': 'Ваканции от пользователей',
            },
        ),
        migrations.CreateModel(
            name='VacancyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_users', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_vacancies', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Избранная ваканция от пользователя',
                'verbose_name_plural': 'Избранные ваканции от пользователей',
            },
        ),
    ]
