# Generated by Django 4.1.5 on 2023-02-13 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_organizationpost_user'),
        ('vacancies', '0002_vacancyfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Ваканция от пользователя', 'verbose_name_plural': 'Ваканции от пользователей'},
        ),
        migrations.AlterModelOptions(
            name='vacancyfavorite',
            options={'verbose_name': 'Избранная ваканция', 'verbose_name_plural': 'Избранные ваканции'},
        ),
        migrations.CreateModel(
            name='OrganizationVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ваканции')),
                ('description', models.TextField(verbose_name='Описание ваканции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_vacancy', to='organizations.organization', verbose_name='Ваканция')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_user_vacancy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ваканция от организации',
                'verbose_name_plural': 'Ваканции от организации',
            },
        ),
    ]
