# Generated by Django 4.1.5 on 2023-02-13 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organizationpost_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0003_alter_vacancy_options_alter_vacancyfavorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationvacancy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_vacancy', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='OrganizationVacancyFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_vacancy_favorite', to='organizations.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_users_favorite', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_vacancies', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Избранная ваканция',
                'verbose_name_plural': 'Избранные ваканции',
            },
        ),
    ]
