# Generated by Django 4.1.5 on 2023-02-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_organizationvacancy_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationvacancyfavorite',
            options={'verbose_name': 'Избранная ваканция от организации', 'verbose_name_plural': 'Избранные ваканции от организации'},
        ),
        migrations.AlterModelOptions(
            name='vacancyfavorite',
            options={'verbose_name': 'Избранная ваканция от пользователя', 'verbose_name_plural': 'Избранные ваканции от пользователей'},
        ),
    ]
