# Generated by Django 4.1.5 on 2023-01-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
