# Generated by Django 4.1.5 on 2023-02-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobtype_skills_typeemployment_workexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_skill', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
