# Generated by Django 4.1.5 on 2023-02-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skills_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
