# Generated by Django 4.1.5 on 2023-02-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_is_premium_remove_user_premium_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='premium',
            new_name='is_premium',
        ),
    ]
