# Generated by Django 4.1.5 on 2023-02-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_trackorganization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpostlike',
            options={'verbose_name': 'Лайки поста организации', 'verbose_name_plural': 'Лайки постов организации'},
        ),
    ]
