# Generated by Django 4.1.5 on 2023-02-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationpostlike_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationpost',
            options={'verbose_name': 'Пост организации', 'verbose_name_plural': 'Посты организации'},
        ),
    ]
