# Generated by Django 4.1.5 on 2023-02-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpost',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations_posts', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
