# Generated by Django 4.1.5 on 2023-02-13 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0007_alter_organizationpost_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_post_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
