# Generated by Django 4.1.5 on 2023-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default=1, max_length=255, verbose_name='Уведомление'),
            preserve_default=False,
        ),
    ]
